logo:
  subtitle: '😇 | 希望开心'

site_tree:
  home:
    leftbar: welcome, recent
    rightbar: timeline

style:
  site:
    background-image: 'url(/images/background.jpeg)'
    blur-px: 10px
    blur-bg: var(--alpha75)