logo:
  subtitle: "🤖 | AI nerd"

site_tree:
  home:
    leftbar: welcome, recent
    rightbar: timeline

style:
  site:
    blur-px: 10px
    blur-bg: var(--alpha75)

plugins:
  sakura:
    enable: true
    inject: |
      <script defer src="/js/sakura.js"></script>
